# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cedar_detect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63\x65\x64\x61r_detect.proto\x12\x0c\x63\x65\x64\x61r_detect\x1a\x1egoogle/protobuf/duration.proto\"\xb7\x01\n\x10\x43\x65ntroidsRequest\x12(\n\x0binput_image\x18\x01 \x01(\x0b\x32\x13.cedar_detect.Image\x12\r\n\x05sigma\x18\x02 \x01(\x02\x12\x10\n\x08max_size\x18\x03 \x01(\x05\x12\x15\n\rreturn_binned\x18\x04 \x01(\x08\x12&\n\x1euse_binned_for_star_candidates\x18\x05 \x01(\x08\x12\x19\n\x11\x64\x65tect_hot_pixels\x18\x06 \x01(\x08\"\x84\x02\n\x0f\x43\x65ntroidsResult\x12\x16\n\x0enoise_estimate\x18\x01 \x01(\x02\x12\x17\n\x0fhot_pixel_count\x18\x02 \x01(\x05\x12\x17\n\x0fpeak_star_pixel\x18\x06 \x01(\x05\x12\x33\n\x0fstar_candidates\x18\x03 \x03(\x0b\x32\x1a.cedar_detect.StarCentroid\x12.\n\x0c\x62inned_image\x18\x04 \x01(\x0b\x32\x13.cedar_detect.ImageH\x00\x88\x01\x01\x12\x31\n\x0e\x61lgorithm_time\x18\x05 \x01(\x0b\x32\x19.google.protobuf.DurationB\x0f\n\r_binned_image\"b\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x12\x17\n\nshmem_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_shmem_name\"n\n\x0cStarCentroid\x12\x33\n\x11\x63\x65ntroid_position\x18\x01 \x01(\x0b\x32\x18.cedar_detect.ImageCoord\x12\x12\n\nbrightness\x18\x04 \x01(\x02\x12\x15\n\rnum_saturated\x18\x06 \x01(\x05\"\"\n\nImageCoord\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x32`\n\x0b\x43\x65\x64\x61rDetect\x12Q\n\x10\x45xtractCentroids\x12\x1e.cedar_detect.CentroidsRequest\x1a\x1d.cedar_detect.CentroidsResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cedar_detect_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CENTROIDSREQUEST']._serialized_start=69
  _globals['_CENTROIDSREQUEST']._serialized_end=252
  _globals['_CENTROIDSRESULT']._serialized_start=255
  _globals['_CENTROIDSRESULT']._serialized_end=515
  _globals['_IMAGE']._serialized_start=517
  _globals['_IMAGE']._serialized_end=615
  _globals['_STARCENTROID']._serialized_start=617
  _globals['_STARCENTROID']._serialized_end=727
  _globals['_IMAGECOORD']._serialized_start=729
  _globals['_IMAGECOORD']._serialized_end=763
  _globals['_CEDARDETECT']._serialized_start=765
  _globals['_CEDARDETECT']._serialized_end=861
# @@protoc_insertion_point(module_scope)
