# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cedar_detect_pb2 as cedar__detect__pb2


class CedarDetectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractCentroids = channel.unary_unary(
                '/cedar_detect.CedarDetect/ExtractCentroids',
                request_serializer=cedar__detect__pb2.CentroidsRequest.SerializeToString,
                response_deserializer=cedar__detect__pb2.CentroidsResult.FromString,
                )


class CedarDetectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractCentroids(self, request, context):
        """Returns INTERNAL error if the Image request's shared memory cannot be accessed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CedarDetectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractCentroids': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractCentroids,
                    request_deserializer=cedar__detect__pb2.CentroidsRequest.FromString,
                    response_serializer=cedar__detect__pb2.CentroidsResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cedar_detect.CedarDetect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CedarDetect(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractCentroids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cedar_detect.CedarDetect/ExtractCentroids',
            cedar__detect__pb2.CentroidsRequest.SerializeToString,
            cedar__detect__pb2.CentroidsResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
